### ISSUE TITLE
navigate 問題

### ISSUE THREAD

**Issue by flyhighhigh** [cosiiine/SE-project#3]
某些頁面，比如新增船員的頁面，在新增完一個船員後，下一次新增船員時，會顯示上一個船員的資料，之後或許可以把某些需要重新渲染的頁面的navigate 改成push pop之類的

**Comment by cosiiine** [comment]
之前是懶得用才沒做啦，需要的話我就加上去
阿像顯示上一筆資料的問題，或許可以在pressHandler把資料reset

**Comment by flyhighhigh** [comment]
解決了
